In [6]:
pip install -e .

Obtaining file:///workspaces/project
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: anndata>=0.10 in ./.venv/lib/python3.11/site-packages (from omicslog==0.1.0) (0.12.10)
Requirement already satisfied: numpy<3.0.0,>=2.0.0 in ./.venv/lib/python3.11/site-packages (from omicslog==0.1.0) (2.3.5)
Requirement already satisfied: array-api-compat>=1.7.1 in ./.venv/lib/python3.11/site-packages (from anndata>=0.10->omicslog==0.1.0) (1.13.0)
Requirement already satisfied: h5py>=3.8 in ./.venv/lib/python3.11/site-packages (from anndata>=0.10->omicslog==0.1.0) (3.15.1)
Requirement already satisfied: legacy-api-wrap in ./.venv/lib/python3.11/site-packages (from anndata>=0.10->omicslog==0.1.0) (1.5)
Requirement already satisfied: natsort in ./.venv/lib/python3.11/site-packages (from anndata>=0.10->omicslog==0.1.0) (8.4.0)
Requirement already satisfied: packaging>=24.2 in ./.venv/lib/python3.11/site-packages (from anndata>=0.10->omicslog==0.1.0) (26.0)
Requirement already satisfied: pandas!=2.1.2,<3,>=2.1.0 in ./.venv/lib/python3.11/site-packages (from anndata>=0.10->omicslog==0.1.0) (2.3.3)
Requirement already satisfied: scipy!=1.17.0,>=1.12 in ./.venv/lib/python3.11/site-packages (from anndata>=0.10->omicslog==0.1.0) (1.16.3)
Requirement already satisfied: zarr!=3.0.*,>=2.18.7 in ./.venv/lib/python3.11/site-packages (from anndata>=0.10->omicslog==0.1.0) (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.11/site-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata>=0.10->omicslog==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.11/site-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata>=0.10->omicslog==0.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.11/site-packages (from pandas!=2.1.2,<3,>=2.1.0->anndata>=0.10->omicslog==0.1.0) (2025.3)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.2,<3,>=2.1.0->anndata>=0.10->omicslog==0.1.0) (1.17.0)
Requirement already satisfied: donfig>=0.8 in ./.venv/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.10->omicslog==0.1.0) (0.8.1.post1)
Requirement already satisfied: google-crc32c>=1.5 in ./.venv/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.10->omicslog==0.1.0) (1.8.0)
Requirement already satisfied: numcodecs>=0.14 in ./.venv/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.10->omicslog==0.1.0) (0.16.5)
Requirement already satisfied: typing-extensions>=4.9 in ./.venv/lib/python3.11/site-packages (from zarr!=3.0.*,>=2.18.7->anndata>=0.10->omicslog==0.1.0) (4.15.0)
Requirement already satisfied: pyyaml in ./.venv/lib/python3.11/site-packages (from donfig>=0.8->zarr!=3.0.*,>=2.18.7->anndata>=0.10->omicslog==0.1.0) (6.0.3)
Building wheels for collected packages: omicslog
  Building editable for omicslog (pyproject.toml) ... done
  Created wheel for omicslog: filename=omicslog-0.1.0-py3-none-any.whl size=1718 sha256=dc6ec973c80cac950637ddf226c06e3733b3b894aed9e8a975c60a224fd85241
  Stored in directory: /tmp/pip-ephem-wheel-cache-407htgir/wheels/37/30/e1/b1863257fe11c57155b308a6dae35341ed577d772e51eb2fc7
Successfully built omicslog
Installing collected packages: omicslog
  Attempting uninstall: omicslog
    Found existing installation: omicslog 0.1.0
    Uninstalling omicslog-0.1.0:
      Successfully uninstalled omicslog-0.1.0
Successfully installed omicslog-0.1.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
from omicslog import log_start
import numpy as np
import pandas as pd
import anndata as ad
from scipy.sparse import csr_matrix
print(ad.__version__)

0.12.10

/tmp/ipykernel_51390/1635567480.py:6: FutureWarning: `__version__` is deprecated, use `importlib.metadata.version('anndata')` instead.
  print(ad.__version__)

In [9]:
counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)

adata.obs_names = [f"Cell_{i:d}" for i in range(adata.n_obs)]
adata.var_names = [f"Gene_{i:d}" for i in range(adata.n_vars)]

logdata = log_start(adata)
print(logdata)

ct = np.random.choice(["B", "T", "Monocyte"], size=(logdata.n_obs,))
logdata.obs["cell_type"] = pd.Categorical(ct)  # Categoricals are preferred for efficiency
print(logdata)
logdata.uns["_omicslog"]

AnnData object with n_obs × n_vars = 100 × 2000
    uns: '_omicslog'
AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'
    uns: '_omicslog'

Operation log:
[2026-05-20 12:12:56] obs: 'cell_type' added

                  Time Operation            Message
0  2026-05-20 12:12:56       obs  'cell_type' added

# Fltrating by Cells (.obs)

In [11]:
logdata = logdata[logdata.obs.cell_type == "B"]
print(logdata)
logdata.uns["_omicslog"]

AnnData object with n_obs × n_vars = 31 × 2000
    obs: 'cell_type'
    uns: '_omicslog'

Empty DataFrame
Columns: [Time, Operation, Message]
Index: []

# Filtering by Genes (.var)

In [12]:
logdata = logdata[:,logdata.var_names.str.endswith("1")]
print(logdata)
logdata.uns["_omicslog"]

AnnData object with n_obs × n_vars = 31 × 200
    obs: 'cell_type'
    uns: '_omicslog'

Operation log:
[2026-05-20 12:14:09] subset: removed 1800 genes (90%), 200 genes remaining

,Time,Operation,Message
0,2026-05-20 12:14:09,subset,"removed 1800 genes (90%), 200 genes remaining"

# Adding observatons and variables

In [13]:
logdata.obsm["X_umap"] = np.random.normal(0, 1, size=(logdata.n_obs, 2))
logdata.varm["gene_stuff"] = np.random.normal(0, 1, size=(logdata.n_vars, 5))
print(logdata)
logdata.uns["_omicslog"]

AnnData object with n_obs × n_vars = 31 × 200
    obs: 'cell_type'
    uns: '_omicslog'
    obsm: 'X_umap'
    varm: 'gene_stuff'

Operation log:
[2026-05-20 12:15:14] varm: 'gene_stuff' added

                  Time Operation             Message
0  2026-05-20 12:15:14      varm  'gene_stuff' added

# Adding layers

In [14]:
logdata.layers["log_transformed"] = np.log1p(logdata.X)
print(logdata)
logdata.uns["_omicslog"]

AnnData object with n_obs × n_vars = 31 × 200
    obs: 'cell_type'
    uns: '_omicslog'
    obsm: 'X_umap'
    varm: 'gene_stuff'
    layers: 'log_transformed'

Operation log:
[2026-05-20 12:16:14] layers: 'log_transformed' added

                  Time Operation                  Message
0  2026-05-20 12:16:14    layers  'log_transformed' added